# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SKIF\Skif_Utility\form_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.adcButton = QtWidgets.QPushButton(self.centralwidget)
        self.adcButton.setGeometry(QtCore.QRect(40, 110, 80, 24))
        self.adcButton.setObjectName("adcButton")
        self.diagButton = QtWidgets.QPushButton(self.centralwidget)
        self.diagButton.setGeometry(QtCore.QRect(40, 150, 111, 24))
        self.diagButton.setObjectName("diagButton")
        self.sdCardReadButton = QtWidgets.QPushButton(self.centralwidget)
        self.sdCardReadButton.setGeometry(QtCore.QRect(40, 190, 111, 24))
        self.sdCardReadButton.setObjectName("sdCardReadButton")
        self.conLabel = QtWidgets.QLabel(self.centralwidget)
        self.conLabel.setGeometry(QtCore.QRect(290, 50, 91, 16))
        self.conLabel.setObjectName("conLabel")
        self.adcLabel = QtWidgets.QLabel(self.centralwidget)
        self.adcLabel.setGeometry(QtCore.QRect(190, 110, 91, 16))
        self.adcLabel.setObjectName("adcLabel")
        self.diagLabel = QtWidgets.QLabel(self.centralwidget)
        self.diagLabel.setGeometry(QtCore.QRect(190, 150, 91, 16))
        self.diagLabel.setObjectName("diagLabel")
        self.readLabel = QtWidgets.QLabel(self.centralwidget)
        self.readLabel.setGeometry(QtCore.QRect(190, 190, 91, 16))
        self.readLabel.setText("")
        self.readLabel.setObjectName("readLabel")
        self.timeHeadLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeHeadLabel.setGeometry(QtCore.QRect(280, 80, 81, 16))
        self.timeHeadLabel.setObjectName("timeHeadLabel")
        self.adcTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.adcTimeLabel.setGeometry(QtCore.QRect(290, 110, 49, 16))
        self.adcTimeLabel.setObjectName("adcTimeLabel")
        self.diagTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.diagTimeLabel.setGeometry(QtCore.QRect(290, 150, 49, 16))
        self.diagTimeLabel.setObjectName("diagTimeLabel")
        self.readTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.readTimeLabel.setGeometry(QtCore.QRect(290, 190, 49, 16))
        self.readTimeLabel.setObjectName("readTimeLabel")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(260, 70, 141, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(40, 50, 160, 24))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.connectButton = QtWidgets.QPushButton(self.splitter)
        self.connectButton.setObjectName("connectButton")
        self.disconnectButton = QtWidgets.QPushButton(self.splitter)
        self.disconnectButton.setObjectName("disconnectButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.adcButton.setText(_translate("MainWindow", "ADC Parse"))
        self.diagButton.setText(_translate("MainWindow", "Diagnostics Parse"))
        self.sdCardReadButton.setText(_translate("MainWindow", "Read from SD Card"))
        self.conLabel.setText(_translate("MainWindow", "Disconnected"))
        self.adcLabel.setText(_translate("MainWindow", "Not Parsed"))
        self.diagLabel.setText(_translate("MainWindow", "Not Parsed"))
        self.timeHeadLabel.setText(_translate("MainWindow", "Elapsed time"))
        self.adcTimeLabel.setText(_translate("MainWindow", "0"))
        self.diagTimeLabel.setText(_translate("MainWindow", "0"))
        self.readTimeLabel.setText(_translate("MainWindow", "0"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))

        
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())