# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SKIF\Skif_Utility\form_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.adcButton = QtWidgets.QPushButton(self.centralwidget)
        self.adcButton.setGeometry(QtCore.QRect(40, 110, 80, 24))
        self.adcButton.setObjectName("adcButton")
        self.diagButton = QtWidgets.QPushButton(self.centralwidget)
        self.diagButton.setGeometry(QtCore.QRect(40, 150, 111, 24))
        self.diagButton.setObjectName("diagButton")
        self.sdCardReadButton = QtWidgets.QPushButton(self.centralwidget)
        self.sdCardReadButton.setGeometry(QtCore.QRect(40, 190, 111, 24))
        self.sdCardReadButton.setObjectName("sdCardReadButton")
        self.conLabel = QtWidgets.QLabel(self.centralwidget)
        self.conLabel.setGeometry(QtCore.QRect(290, 50, 91, 16))
        self.conLabel.setObjectName("conLabel")
        self.adcLabel = QtWidgets.QLabel(self.centralwidget)
        self.adcLabel.setGeometry(QtCore.QRect(190, 110, 91, 16))
        self.adcLabel.setObjectName("adcLabel")
        self.diagLabel = QtWidgets.QLabel(self.centralwidget)
        self.diagLabel.setGeometry(QtCore.QRect(190, 150, 91, 16))
        self.diagLabel.setObjectName("diagLabel")
        self.readLabel = QtWidgets.QLabel(self.centralwidget)
        self.readLabel.setGeometry(QtCore.QRect(190, 190, 91, 16))
        self.readLabel.setText("")
        self.readLabel.setObjectName("readLabel")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(40, 50, 160, 24))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.connectButton = QtWidgets.QPushButton(self.splitter)
        self.connectButton.setObjectName("connectButton")
        self.disconnectButton = QtWidgets.QPushButton(self.splitter)
        self.disconnectButton.setObjectName("disconnectButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.adcButton.setText(_translate("MainWindow", "ADC Parse"))
        self.diagButton.setText(_translate("MainWindow", "Diagnostics Parse"))
        self.sdCardReadButton.setText(_translate("MainWindow", "Read from SD Card"))
        self.conLabel.setText(_translate("MainWindow", "Disconnected"))
        self.adcLabel.setText(_translate("MainWindow", "Not Parsed"))
        self.diagLabel.setText(_translate("MainWindow", "Not Parsed"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
